### ISSUE TITLE
Rename package to @omnisci/omnisci.js

### ISSUE THREAD

**Issue by domoritz** [heavyai/heavyai-connector#161]
Since MapD is now OmniSci, it would make sense to rename this repo and the corresponding npm package.

**Comment by domoritz** [comment]
Blocking https://github.com/omnisci/vega-transform-omnisci-core/issues/3

**Comment by jrajav** [comment]
@domoritz Thanks for the suggestion!

We plan to do this, but we are going to coordinate it with our next major release (coming within the next few months), and the planned name right now is `@omnisci/omnisci.js` to disambiguate with other client libraries.

**Comment by jrajav** [comment]
@domoritz Just an update on this (since we just published 5.1.0) - we're still planning this move, but it will come in release 5.2, along with other updates to namespace packages into `@omnisci`. We'll be sure to consider vega-transform-omnisci-core at the same time, then. Thanks for being engaged!

**Comment by domoritz** [comment]
5.2 is out and breaking my builds in Falcon right now. `@omnisci/omnisci.js` doesn't seem to be online yet. Is it coming and will the browser build be compatible with bundlers such as rollup?

**Comment by xmnlab** [comment]
hi everyone! is there any ETA for this?

**Comment by domoritz** [comment]
I guess now it's heavyai-connector.

**Comment by domoritz** [comment]
Looks like this happened. https://github.com/heavyai/heavyai-connector#quick-start-for-users
