### ISSUE TITLE
Update arrow library

### ISSUE THREAD

**Issue by domoritz** [heavyai/heavyai-connector#224]
Version 3 is out and Version 4 will be released soon.

**Comment by domoritz** [comment]
Version 4.0.1 is out.

**Comment by domoritz** [comment]
Version 5 is out.

**Comment by domoritz** [comment]
Version 6 is out.

**Comment by domoritz** [comment]
Version 7 is out.

**Comment by bmatcuk** [comment]
Updated to v7 in https://github.com/heavyai/heavyai-connector/pull/276

**Comment by domoritz** [comment]
Wohoo. Thanks for working on the update. Will you make a release and fix https://github.com/heavyai/heavyai-connector/issues/272?
