### ISSUE TITLE
@heavyai/connector does not exist

### ISSUE THREAD

**Issue by domoritz** [heavyai/heavyai-connector#272]
https://www.npmjs.com/package/@heavyai/connector is not a released package.

**Comment by bmatcuk** [comment]
Published: https://www.npmjs.com/package/@heavyai/connector

**Comment by domoritz** [comment]
Are you also updating https://www.npmjs.com/package/@mapd/connector or should everyone move to the other package? If the latter, you should probably issue a deprecation notice.
