### ISSUE TITLE
ReferenceError: window is not defined for node-connector

### ISSUE THREAD

**Issue by tsaist1** [heavyai/heavyai-connector#274]
I am trying to connect to omniscidb from my node server however I've ran into the following issue. Following the example here https://github.com/heavyai/heavyai-connector/blob/master/examples/node.js

I am getting 
```
node_modules/@heavyai/connector/dist/node-connector.js:1062
          return window.location.protocol.replace(":", "");
          ^

ReferenceError: window is not defined
```

node v16.14.2

**Comment by bmatcuk** [comment]
I'm looking into this, but I _believe_ you can fix the issue by calling either `.protocol("http")` or `.protocol("https")`, depending on your setup, in addition to `.host(...)` and `.port(...)`.
